# Generated by Django 5.2.4 on 2025-08-02 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, help_text='Street address for emergency services')),
                ('allergies', models.TextField(blank=True)),
                ('pre_existing_conditions', models.TextField(blank=True, help_text='List any chronic illnesses or important conditions.')),
                ('emergency_notes', models.TextField(blank=True, help_text="Any extra info for first responders (e.g., 'At risk of stroke, heart problems').")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
