# Generated by Django 5.2.4 on 2025-08-03 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_verified_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('priority_score', models.IntegerField(default=1, help_text='Priority from 1 (lowest) to 10 (highest urgency)')),
                ('estimated_service_time', models.IntegerField(default=30, help_text='Estimated time in minutes for service')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from hospital staff')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_queue', to='api.hospitalprofile')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', 'admitted_at'],
                'unique_together': {('hospital', 'patient')},
            },
        ),
    ]
