# Generated by Django 5.2.4 on 2025-08-03 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hospitalprofile_latitude_hospitalprofile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', models.TextField(help_text="Patient's description of their symptoms/condition")),
                ('patient_latitude', models.DecimalField(decimal_places=6, help_text="Patient's location when request was made", max_digits=9)),
                ('patient_longitude', models.DecimalField(decimal_places=6, help_text="Patient's location when request was made", max_digits=10)),
                ('ai_reasoning', models.TextField(help_text="AI's explanation for hospital choice")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_requests', to=settings.AUTH_USER_MODEL)),
                ('recommended_hospital', models.ForeignKey(help_text='Hospital recommended by AI', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='api.hospitalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
