# Generated by Django 5.2.4 on 2025-08-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_hospitalrequest_patient_latitude_and_more'),
        ('api', '0008_fix_coordinates'),
    ]

    operations = [
    ]
