# Generated by Django 5.2.4 on 2025-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250803_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrequest',
            name='patient_latitude',
            field=models.DecimalField(decimal_places=15, help_text="Patient's location when request was made", max_digits=20),
        ),
        migrations.AlterField(
            model_name='hospitalrequest',
            name='patient_longitude',
            field=models.DecimalField(decimal_places=15, help_text="Patient's location when request was made", max_digits=20),
        ),
    ]
