# Generated by Django 5.2.4 on 2025-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_hospitalrequest_patient_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrequest',
            name='urgency_score',
            field=models.IntegerField(default=5, help_text='AI-assessed urgency (1-10)'),
        ),
    ]
